
#ifndef _FSL_SSS_CONFIG_H_
#define _FSL_SSS_CONFIG_H_

#define SSS_SESSION_MAX_CONTEXT_SIZE 4
#define SSS_KEY_STORE_MAX_CONTEXT_SIZE 64
#define SSS_KEY_OBJECT_MAX_CONTEXT_SIZE 64
#define SSS_SYMMETRIC_MAX_CONTEXT_SIZE 80
#define SSS_AEAD_MAX_CONTEXT_SIZE 4
#define SSS_DIGEST_MAX_CONTEXT_SIZE 80
#define SSS_MAC_MAX_CONTEXT_SIZE 4
#define SSS_ASYMMETRIC_MAX_CONTEXT_SIZE 64
#define SSS_TUNNEL_MAX_CONTEXT_SIZE 4
#define SSS_DERIVE_KEY_MAX_CONTEXT_SIZE 64

#endif /* _FSL_SSS_CONFIG_H_ */
